import React from 'react';
import { 
  LayoutDashboard, 
  DraftingCompass, 
  Server, 
  ShieldCheck, 
  Activity, 
  Terminal, 
  Lock, 
  Globe, 
  FileText, 
  Settings,
  Database,
  CalendarDays,
  Rocket,
  Search,
  Sparkles,
  MessageSquare,
  Image as ImageIcon
} from 'lucide-react';
import { Vendor } from './types';

export const SYSTEM_PROMPT = `
### SYSTEM IDENTITY & ROLE
You are "NetGenius Enterprise Core," the central intelligence of a Tier-1 Network Automation & Orchestration Platform.
TARGET AUDIENCE: Government Ministries, Public Sector Universities, and Large Enterprises in Pakistan & MENA Region.
VERSION: Commercial Edition v2.0 (Stable).

### CORE DIRECTIVES (NON-NEGOTIABLE)
1. PROFESSIONALISM: Maintain a rigid, Executive-Level tone (CIO/NOC Manager persona). No filler words, no emojis, no slang. Use industry-standard terminology (ITIL, TOGAF).
2. SECURITY FIRST: Adhere to NIST 800-53 and ISO 27001 standards. Never generate code with default passwords (e.g., 'cisco', 'admin'). Always prompt for RBAC (Role-Based Access Control) verification before critical changes.
3. ACCURACY: If a network configuration parameter is ambiguous, ASK clarifying questions. Do not assume IP schemas or VLAN IDs.
4. FORMATTING: All technical output must be inside Markdown code blocks. All executive summaries must be bulleted.

### KNOWLEDGE DOMAIN
- Vendors: Cisco (IOS/NX-OS), Juniper (Junos), Huawei (VRP), Fortinet, MikroTik, Aruba, Ubiquiti, Palo Alto.
- Protocols: BGP, OSPF, MPLS, VXLAN, SD-WAN, SNMP, NetFlow.
- Compliance: PEC (Pakistan Engineering Council) Standards, PTA Regulations, NIST.

### FUNCTIONAL MODULES & BEHAVIORS
[MODULE 1: DASHBOARD & KPI]
- When asked for status: Provide specific metrics (Uptime, Jitter, Latency, Packet Loss).
- Context: Highlight critical alarms (P1/P2) immediately.

[MODULE 2: INTENT DESIGNER (Architecture)]
- Input: User describes requirements in natural language (Urdu/English).
- Output: Generate a structured High-Level Design (HLD) and Low-Level Design (LLD).
- Action: Suggest hardware models based on budget and throughput requirements.

[MODULE 3: CONFIG ENGINE (Production Code)]
- STAGE 1: Analyze intent.
- STAGE 2: Generate syntax-perfect CLI commands.
- STAGE 3: Add "Rollback" configuration safety scripts.
- WARNING: Always include a disclaimer: "Verify in Lab Environment before deploying to Production."

[MODULE 4: AI VISUAL LAB (Multi-Modal)]
- Cabling Analysis: Identify Spaghetti cabling, damaged fiber connectors, or improper airflow.
- Topology: Describe visualizations hierarchically (Core -> Dist -> Access).

[MODULE 5: AUDIT & COMPLIANCE]
- Check configs for: Telnet enabled (Fail), HTTP server enabled (Fail), Weak Encryption (Fail).
- Report: Generate a "Compliance Scorecard" (0-100%).

### RESPONSE PROTOCOLS
1. IF USER ASKS FOR CODE:
- Provide the specific vendor syntax.
- Comment every significant line of code (Best Practice).
2. IF USER REPORTS AN OUTAGE:
- Follow standard Troubleshooting steps: Layer 1 (Physical) -> Layer 2 (Data Link) -> Layer 3 (Routing).
3. IF USER ASKS NON-NETWORK QUESTIONS:
- Politely decline: "My capabilities are restricted to Network Infrastructure and IT Operations. Please refer to general support."

### LOCALIZATION CONTEXT (PAKISTAN)
- Be aware of local power constraints (UPS/Solar integration for NOCs).
- Prioritize availability of hardware common in the local market.

### OUTPUT TEMPLATE (Strictly Follow This Structure)
**[MODULE NAME] Request Processing**
**Status:** [Analyzing/Generating/Auditing]
**Severity:** [Info/Warning/Critical]
**Executive Summary:** [Brief explanation of the action taken]
**Technical Output:** \`\`\`[Language/Vendor] [Code or Data goes here] \`\`\`
**Next Steps / Recommendations:**
1. [Step 1]
2. [Step 2]
---
*Generated by NetGenius AI | Enterprise License*

Designed & Developed by Mr. Zeeshan Javed
AI System Architect & Network Automation Specialist
`;

export const ARCHITECT_TEMPLATES = [
  {
    title: "University Campus",
    prompt: "Design a university network for 5 departments. Require OSPF, dual ISP load balancing, and secure student WiFi portal."
  },
  {
    title: "Secure Govt Office",
    prompt: "Secure Govt office network with air-gapped zones, strict audit logging, and NIST compliance using Fortinet firewalls."
  },
  {
    title: "Enterprise HQ",
    prompt: "Multi-vendor HQ deployment with Cisco Core, MikroTik Branch VPNs, and Ubiquiti Wireless density optimization."
  }
];

export const PROPOSAL_TEMPLATES = [
  {
    id: 'uni',
    title: "University Smart-Campus Proposal",
    target: "Director IT / Vice Chancellor",
    description: "AI-driven centralized management for large educational institutions."
  },
  {
    id: 'govt',
    title: "Government Infrastructure Modernization",
    target: "Secretary IT / Director General",
    description: "NIST compliant, secure network automation for government departments."
  },
  {
    id: 'tender',
    title: "Official Tender Response (Pakistan Govt)",
    target: "Procurement Committee / Secretary IT",
    description: "Formal bid response following standard govt procurement protocols."
  }
];

export const MOCK_DEVICES = [
  { id: '1', name: 'CORE-RT-01', vendor: Vendor.CISCO, model: 'Catalyst 9500', role: 'Router', ipAddress: '10.0.0.1', status: 'Online', healthScore: 98, ztp: 'Provisioned' },
  { id: '2', name: 'CAMPUS-SW-01', vendor: Vendor.JUNIPER, model: 'EX4300', role: 'Switch', ipAddress: '10.0.0.5', status: 'Online', healthScore: 94, ztp: 'Provisioned' },
  { id: '3', name: 'SEC-FW-01', vendor: Vendor.FORTINET, model: 'FortiGate 100F', role: 'Firewall', ipAddress: '10.0.0.2', status: 'Alerting', healthScore: 72, ztp: 'Manual' },
  { id: '4', name: 'WIFI-WLC-01', vendor: Vendor.UBIQUITI, model: 'Dream Machine Pro', role: 'WLC', ipAddress: '10.0.0.10', status: 'Online', healthScore: 88, ztp: 'Provisioned' },
  { id: '5', name: 'DEPT-SW-02', vendor: Vendor.MIKROTIK, model: 'CRS326', role: 'Switch', ipAddress: '10.0.1.20', status: 'Online', healthScore: 99, ztp: 'Pending' },
];

export const NAV_ITEMS = [
  { id: 'dashboard', label: '1. Dashboard', icon: <LayoutDashboard className="w-5 h-5" /> },
  { id: 'inventory', label: '2. Sites & Assets', icon: <Server className="w-5 h-5" /> },
  { id: 'architect', label: '3. Intent Designer', icon: <DraftingCompass className="w-5 h-5" /> },
  { id: 'deployment', label: '5. Deployment Mgr', icon: <Rocket className="w-5 h-5" /> },
  { id: 'ai_lab', label: '6. AI Visual Lab', icon: <ImageIcon className="w-5 h-5" /> },
  { id: 'compliance', label: '7. Audit & Compliance', icon: <ShieldCheck className="w-5 h-5" /> },
  { id: 'reports', label: '8. Reports & Export', icon: <FileText className="w-5 h-5" /> },
  { id: 'architecture', label: 'System Architecture', icon: <Database className="w-5 h-5" /> },
  { id: 'roadmap', label: 'Development Roadmap', icon: <CalendarDays className="w-5 h-5" /> },
  { id: 'settings', label: 'Platform Settings', icon: <Settings className="w-5 h-5" /> },
];